steps:
  # 1. Backend Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/caffeine-server', './server']

  # 2. Frontend Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/caffeine-web', '.']

  # 3. 이미지 푸시 (Container Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/caffeine-server']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/caffeine-web']

  # 4. Deploy the backend service with the pre-built image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "app"
      - "deploy"
      - "server/app.yaml"
      - "--image-url=gcr.io/$PROJECT_ID/caffeine-server"
      - "--project=$PROJECT_ID"
      - "--quiet"

  # 5. Deploy the default (frontend) service with the pre-built image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "app"
      - "deploy"
      - "app.yaml"
      - "--image-url=gcr.io/$PROJECT_ID/caffeine-web"
      - "--project=$PROJECT_ID"
      - "--quiet"

images:
  - 'gcr.io/$PROJECT_ID/caffeine-server'
  - 'gcr.io/$PROJECT_ID/caffeine-web'

