# Google App Engine Flexible Environment 설정
# Dockerfile을 기반으로 배포하기 위해 runtime: custom 및 env: flex를 사용합니다.
runtime: custom
env: flex

# 서비스 이름
# 백엔드를 backend 서비스로 배포합니다.
service: backend

# 하드웨어 리소스 설정 (비용 최적화를 위해 최소 사양으로 설정됨, 필요시 조정)
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# 오토스케일링 설정
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

# 환경 변수
env_variables:
  NODE_ENV: 'production'

# 네트워크 설정 (필요한 경우)
# network:
#   name: default
